name: Leak Detector

on:
  push:

jobs:
  test:
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 58080:80
    strategy:
      matrix:
        version: [18, 19, 20]
    runs-on: ubuntu-latest
    name: Test on Node v${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        run: npm i
      - name: Test
        run: npm test
