name: Leak Detector

on:
  push:

jobs:
  test:
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 58080:80
    strategy:
      fail-fast: false
      matrix:
        version: [18, 20, 21]
        type: ["cjs", "esm"]
    runs-on: ubuntu-latest
    name: Test on Node v${{ matrix.version }} with ${{ matrix.type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        run: npm i
      - name: Test
        run: npm run test:${{ matrix.type }}
